name: Run Tests with Bun

on:
  push:
    branches: ["*"]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun lint

      - name: Build Code
        run: bun run build

      - name: Build Code
        run: bun run typecheck

      - name: Run tests
        run: bunx ava  --timeout=2m
